---

# INSTALL JAVA 8
- name: Ensure Java is installed.
  apt: "name={{ item }} state=present"
  with_items:
   - openjdk-8-jdk

- name:  Install apt-transport-https to support https APT downloads
  apt: name=apt-transport-https state=present

- name: Download Elasticsearch
  get_url:
    url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}.deb"
    dest: /tmp

- name: Install Elasticsearch
  apt: deb="/tmp/elasticsearch-{{ elasticsearch_version }}.deb"

- name: config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/elasticsearch/{{ item }}"
  with_items:
    - jvm.options
    - elasticsearch.yml
    - logging
  notify:
    - restart elasticsearch

- name: daemon config
  template:
    src: elasticsearch.j2
    dest: /etc/default/elasticsearch
    owner: root
    group: root
    mode: 0644
  notify:
    - restart elasticsearch

- name: Install elasticsearch plugins
  command: "/usr/share/elasticsearch/bin/elasticsearch-plugin install {{ item.plugin }} --batch --silent"
  with_items: "{{ es_plugins }}"
  notify: restart elasticsearch


- name: service start
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ elasticsearch_daemon }}"

- name: wait for service start
  wait_for:
    port: "{{ elasticsearch_http_port }}"
    delay: 3
    timeout: 45