---

# INSTALL JAVA 8
- name: Add Oracle Java Repository
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java 8 Licence
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | tee /etc/oracle-java-8-licence-acceptance | /usr/bin/debconf-set-selections
  args:
    creates: /etc/oracle-java-8-licence-acceptance

- name: Install Oracle Java 8
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default

- name:  Install apt-transport-https to support https APT downloads
  apt: name=apt-transport-https state=present

- name: Download Elasticsearch
  get_url:
    url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0.deb"
    dest: /tmp

- name: Install Elasticsearch
  apt: deb="/tmp/elasticsearch-6.0.0.deb"

- name: config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/elasticsearch/{{ item }}"
  with_items:
    - jvm.options
    - elasticsearch.yml
    - logging
  notify:
    - restart elasticsearch

- name: daemon config
  template:
    src: elasticsearch.j2
    dest: /etc/default/elasticsearch
    owner: root
    group: root
    mode: 0644
  notify:
    - restart elasticsearch

- name: Install elasticsearch plugins
  command: "/usr/share/elasticsearch/bin/elasticsearch-plugin install {{ item.plugin }} --batch --silent"
  with_items: "{{ es_plugins }}"
  notify: restart elasticsearch


- name: service start
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ elasticsearch_daemon }}"

- name: wait for service start
  wait_for:
    port: "{{ elasticsearch_http_port }}"
    delay: 3
    timeout: 45