---

- name: Add Oracle Java Repository
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java 8 Licence
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | tee /etc/oracle-java-8-licence-acceptance | /usr/bin/debconf-set-selections
  args:
    creates: /etc/oracle-java-8-licence-acceptance

- name: Install Oracle Java 8
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default

- name: Download Elasticsearch
  get_url:
    url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ es_version }}.deb"
    dest: /tmp

- name: Install Elasticsearch
  apt: deb="/tmp/elasticsearch-{{ es_version }}.deb"

- name: Configure Elasticsearch.
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0750

- name: Install elasticsearch plugins
  command: "{{es_home}}/bin/elasticsearch-plugin install {{ item.plugin }} --batch --silent"
  with_items: "{{ es_plugins }}"
  notify: restart elasticsearch
  
# Fix permissions
- file:
    path: /usr/share/elasticsearch/plugins
    state: directory
    owner: elasticsearch
    group: elasticsearch
    recurse: yes

- name: Make sure Elasticsearch is running before proceeding.
  wait_for: host={{ elasticsearch_network_host }} port={{ elasticsearch_http_port }} delay=3 timeout=300

